Work around buggy Emacs native-compile
For reasons beyond sense or comprehension, the inclusion of the form:

    (capitalize mute-str)

...in `mastodon-tl--mute-or-unmute-thread` causes native compilation of mastodon.el to fail with:

    Error: invalid-function ("mastodon-tl.el" #<subr or>)

This makes no sense, and should be reported upstream.  In the mean time, trading a capitalized prompt string for a working native-compile seems like an easy win.

fixes #715, fixes #536.