Fix broken `sort` call.
This code was calling `sort`, but should have called `cl-sort`.  This causes a warning when byte-compiling:

    mastodon-tl.el:3095:19: Warning: ‘sort’ called with 3 arguments, but accepts only 2

...and pages of baffling errors when native-compiling:

    Error: native-compiler-error ("mastodon-tl.el" "Compiling /home/ieure/projects/emacs/mastodon.el/lisp/mastodon-tl.eln...
    libgccjit.so: error: gcc_jit_context_new_call_through_ptr: too many arguments to fn_ptr: freloc->R736f7274_sort_0 (got 3 args, expected 2)
    Internal native compiler error: \"gcc_jit_context_new_call_through_ptr: too many arguments to fn_ptr: freloc->R736f7274_sort_0 (got 3 args, expected 2)\"

Calling the correct function resolves both.